"""Functions for installing the state_exporter mod to a Factorio installation."""

import shutil
from pathlib import Path


def mod_file_path() -> str:
    """Returns the path to the mod directory on disk."""
    return str(Path(__file__).parent / "mod")


def install_mod(factorio_path: str | Path, port_num: int, verbose: bool) -> None:
    """Install the state_exporter mod to the specified Factorio installation.

    Args:
        factorio_path: Path to the Factorio installation directory
        port_num: UDP port number for state communication
        verbose: Whether to enable verbose logging in the mod
    """
    factorio_path = Path(factorio_path)
    mod_source = Path(mod_file_path())
    mod_dest = factorio_path / "mods" / "state-exporter"

    # Copy mod directory, overwriting if it exists
    if mod_dest.exists():
        shutil.rmtree(mod_dest)
    shutil.copytree(mod_source, mod_dest)

    autogen_warning = (
        "-- This file is auto-generated by settings.lua.tpl. Edit that file if you\n"
        "-- want your changes to be persistent."
    )
    verbose_str = "true" if verbose else "false"
    settings_content = f"""{autogen_warning}

return {{port_num = {port_num}, verbose = {verbose_str}}}
"""
    settings_path = mod_dest / "settings.lua"
    settings_path.write_text(settings_content)
